### ISSUE TITLE
Assertion failed: Typed arrays 2 must be run on a little-endian system

### ISSUE THREAD

**Issue by smartmouse** [gevorg/apache-crypt#8]
> apache-crypt@1.0.8 test /home/nodebot/test/node_modules/apache-crypt
> node ./node_modules/nodeunit/bin/nodeunit tests

Assertion failed: Typed arrays 2 must be run on a little-endian system
Assertion failed: Typed arrays 2 must be run on a little-endian system
TAP version 13
1..0
# time=76.541ms

/home/nodebot/test/node_modules/apache-crypt/lib/libcrypt.js:1
orts, require, module, __filename, __dirname) { function f(a){throw a;}var h=v
                                                                    ^
abort() at Error
    at Error (<anonymous>)

Is it possible to support big-endian system?

**Comment by gevorg** [comment]
I guess it is possible, but I don't know how to do that. 
I will accept any pull request that will add big-endian system support. Gevorg

**Comment by richardpringle** [comment]
Hey gevorg! I was thinking of taking a look into the problem, do you have a copy of the libcrypt.js that I can read? Thanks in advance!

**Comment by gevorg** [comment]
Hey Richard! Thanks, actually libcrypt.js is being generated from C files using https://github.com/kripken/emscripten , you can look https://github.com/gevorg/apache-crypt/commit/43780a2d4632e05913a2bda702bd140d5d0cbca5 for more details. Gevorg

**Comment by smartmouse** [comment]
Thanks gevorg for your quick response and Richard for stepping in :-)

**Comment by richardpringle** [comment]
While looking for a solution, I came across the https://github.com/gevorg/apache-md5 module. Is there a specific reason that you haven't implemented the remaining algorithms the same was as your other module? That module looks a lot better since it actually uses the native crypto module to run the encryption algorithm.

**Comment by gevorg** [comment]
Agree, no specific reason, I just didn't invest time for doing that. Gevorg

**Comment by gevorg** [comment]
Please recheck, thanks to Richard issue must be resolved now. Gevorg
